apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-angularapp
spec:
  replicas: 1  # Set the desired number of replicas
  selector:
    matchLabels:
      app: my-angularapp
  template:
    metadata:
      labels:
        app: my-angularapp
    spec:
      containers:
      - name: my-angularapp
        image: rohithkalla/28-2-angular/my-angularapp-image:latest  # Replace with your actual image and version
        ports:
        - containerPort: 80
